### ISSUE TITLE
There seems to be some code missing here

### ISSUE THREAD

**Issue by byronzhu-haha** [OpsPAI/Prism#1]
https://github.com/OpsPAI/Prism/blob/fbc7a2a8a227a635c43b3e9c49be20f434a5120b/src/MultiLevelClustering.py#L200-L209

**Comment by JinYang88** [comment]
Hi, thanks for your attention to our work. 

We have deliberately included a switch here to indicate whether to use the variance as the weight or not. You can control this through the weighted_matrix variable.

**Comment by byronzhu-haha** [comment]
Ok, thanks for your reply! I seem to understand something.
In addition, I am still confused that I did not find the definition of variables `len` and `row_variances`. Where they come from. Hope to hear from you again.
Grateful!

**Comment by zhjiang22** [comment]
Hi, thank you for bringing this to our attention. The problem arose due to our inadvertent deletion of certain lines of code in our debugging procedure. We have fixed the issue and updated the code accordingly. Please review the latest version.
